Python/django/mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from django.views import static
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^book/',include('bookapp.urls')),
    url(r'^blog/',include('blogapp.urls')),
    url(r'^',include('usr.urls')),
    url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'^favicon\.ico/$',RedirectView.as_view(url='/static/7.png'),name = 'favicon'),
    # url(r'^',include('usr.user'))

]

Python/django/mysite/usr/urls.py
#coding=utf-8
from django.conf.urls import url
from usr.views import *
urlpatterns = [
    url(r'^index/$',index),
    url(r'^search_form/$',search_form),
    # url(r'^contact/$',contact),
    # url(r'^contact/thanks/$',thanks),
]



urlpatterns += [
    url(r'^request$',get_request),
    url(r'^formset/$',formset),
    url(r'^bookset/$',bookset),
]

#login
# urlpatterns += [
# url(r'^login/$',login),
# url(r'^index/$',index),
# url(r'^logout/$',logout),
# ]

urlpatterns += [
url(r'^login/$',login),
url(r'^logout/$',logout),
url(r'^login_test/$',login_test),
url(r'^reg/$',reg,name = 'reg'),
url(r'^thanks/$',thanks),
url(r'^avatar/$',avatar),
url(r'^img/$',img),
url(r'^page/$',get_page),

]

urlpatterns += [
url(r'^cache/$',cache),
]

Python/django/mysite/usr/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    avatar = models.ImageField(upload_to = 'avater/%Y/%m',default ='/static/default.png ',max_length = 200,blank = True,verbose_name = 'Head_portrait')
    mobile = models.CharField(max_length = 11,blank = True, null = True , verbose_name = 'tel')
    class Meta:
        verbose_name = 'User'
        ordering = ['-id']
    def __unicode__(self):
        return self.username

Python/django/mysite/usr/forms.py
#coding=utf-8
from django import forms
from  bookapp.models import Book,Author

TOPIC_CHOICES = (
    ('leve1','好评'),
    ('leve2','中评'),
    ('leve3','差评'),
)

class RemarkForm(forms.Form):
    subject = forms.CharField(max_length = 100,label = '标题')
    mail = forms.EmailField(label = '邮件')
    topic = forms.ChoiceField(choices = TOPIC_CHOICES,label = '评价')
    message = forms.CharField(label = '内容',widget = forms.Textarea)
    cc_myself = forms.BooleanField(required = False,label = '订阅')

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'
        labels = {
            'first_name':'标题',
        }
class RegForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Username","required":"required"}),max_length=50,error_messages = {"required":"Username can not be empty"})
    password=forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password","required":"required"}),max_length=20,error_messages = {"required":"password can not be empty"})
    email=forms.EmailField(widget=forms.TextInput(attrs={"placeholder":"Email","required":"required"}),max_length=50,error_messages = {"required":"Email can not be empty"})
    tel=forms.CharField(widget=forms.TextInput(attrs={"placeholder":"telephone","required":"required"}),max_length=50,error_messages = {"required":"telephone can not be empty"})
    avatar = forms.ImageField(required = False)

Python/django/mysite/usr/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from forms import *
from bookapp.models import Author
from django.views.decorators.csrf import csrf_exempt
from django.contrib.sessions.models import Session
from django.contrib import auth
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required,permission_required
from usr.models import *
from django.core.paginator import Paginator,InvalidPage,EmptyPage,PageNotAnInteger
# Create your views here.
def index(request):
    # index = dir(request)
    # return HttpResponse(index)
    return render(request,'search.html',{})
def search_form(request):
    print request.method
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        return HttpResponse('I have get the %s '%q)
    else:
        return render(request,'search.html',{'error':True})

# def contact(request):
def get_request(request):
    scheme = request.scheme
    body = request.body
    path = request.path
    method = request.method
    content = request.content_type
    get = request.GET
    post = request.POST
    cook = request.COOKIES
    meta = request.META
    addr = request.META['REMOTE_ADDR']
    print request.get_host()
    # url = request.get('HTTP_REFERER','SORRY')

    return render(request,'request.html',locals())


def formset(request):
    if request.method == 'POST':
        form = RemarkForm(request.POST)
        if form.is_valid():
            cd  = form.cleaned_data
            print cd['subject']
            print cd['mail']
            print cd['topic']
            print cd['message']
            print cd['cc_myself']
            return HttpResponseRedirect('/formset')
    else:
        form = RemarkForm()

    return render(request,'formset.html',{'form':form})


def bookset(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            cd  = form.cleaned_data
            dic = {'first_name':cd['first_name'],'last_name':cd['last_name'],'email':cd['email']}
            Author.objects.create(**dic)
            return HttpResponseRedirect('/bookset/')
    else:
        form = AuthorForm()

    return render(request,'bookset.html',{'form':form})



#########session
# user_info = {
# 'pangzi':{'pwd':'pang123'},
# 'shouzi':{'pwd':'shou321'}
# }
# @csrf_exempt
# def login(request):
#     if request.method =='GET':
#         return render(request,'login.html')
#     if request.method == 'POST':
#         u = request.POST.get('username')
#         p = request.POST.get('pwd')
#         dic = user_info.get(u)
#         if not dic:
#             return render(request,'login.html')
#         if dic['pwd'] == p:
#             request.session['username'] = u
#             request.session['is_login'] = True
#             request.session.set_expiry(20)
#             res = redirect('/index/')
#             return res
#         else:
#             return render(request,'login.html')
# def index(request):
#     if request.session.get('is_login',None):
#         session = Session.objects.all()
#         print session
#         return render(request,'index1.html',{'current_user':request.session['username']})
#     else:
#         return redirect('/login/')
#
# def logout(request):
#     print dir(request.session)
#     request.session.clear()
#     return redirect('/login/')


# user_info = {
# 'pangzi':{'pwd':'pang123'},
# 'shouzi':{'pwd':'shou321'}
# }
# @csrf_exempt#form 表单错误处理
# def login(request):
#     if request.method == 'POST':
#         u = request.POST.get('username')
#         p = method == 'POST':
#         u = request.POST.get('username')
#         p = req.POST.get('pwd')
#         dic = user_info.get(u)
#         if not dic:
#             return render(request,'login.html')
#         if dic['pwd'] == p:
#             res = redirect('/index/')
#             res.set_cookie('user',u,max_age = 60,path = '/')
#             return res
#         else:
#             return render(request,'login.html')
# def index(request):
#     v = request.COOKIES.get('user')
#     if not v:
#         return redirect('/login/')
#     return render(request,'index1.html',{'current_user':v})


#########################
@login_required(login_url = '/login/')#登录后才允许
def login_test(request):
    return HttpResponse('Thank you for login')
def login(request):
    errors = []
    if request.method == 'POST':
        username = request.POST.get('username','')
        password = request.POST.get('password','')
        if not username:
            errors.append('Enter a username')
        if not password:
            errors.append('Enter a password')
        if not errors:
            if not request.user.is_authenticated():
                user = auth.authenticate(username =username ,password = password)#检查是否合法
                if user is not None and user.is_active:
                    auth.login(request,user)
                    # return HttpResponseRedirect(request.META.get("HTTP_REFERER",'/'))
                    return HttpResponseRedirect(request.GET.get("next",'/'))
                else:
                    return HttpResponse('username or password invalid')
            else:
                return HttpResponse('You have already login')
    return render(request,'user_login.html',{'errors':errors})
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/login/')


#################
def thanks(request):
    return HttpResponse('Thanks for your register')
@permission_required('add_User',login_url = '/thanks')##change_user,delete_user 是否允许注册
def reg(request):
    try:
        if request.method == 'POST':
            reg_form = RegForm(request.POST)
            if reg_form.is_valid():
                cd = reg_form.cleaned_data
                User.objects.create(username=cd['username'],password=make_password(cd['password']),email=cd['email'],mobile=cd['tel'],avatar = cd['avatar'])

                return HttpResponseRedirect("/login/")
            else:
                return render(request,'failure.html',{'reason':reg_form.errors})
        else:
            reg_form = RegForm()
    except Exception as e:
        print e
    return render(request,'reg.html',locals())

def img(request):
    return render(request,'avatar.html')

def avatar(request):
    pass




def get_page(request):

    article_list = ['a1','a2','a3','a4','a5','a6','a7','a8']
    paginator = Paginator(article_list,5)
    p = int(request.GET.get('page',1))
    article_list = paginator.page(p)
    return render(request,'page.html',{'article_list':article_list})

# 2.某一个页面进行缓冲
from django.views.decorators.cache import cache_page
@cache_page(10)
def cache(request):
    import time
    ctime = time.time()
    return render(request,'cache.html',{'ctime':ctime})

Python/django/mysite/usr/templates/avatar.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>图像上传</title>
  </head>
  <body>
    <form class="" action="/avatar/" method="post" >
      {%csrf_token%}
			<input type="file" name="avatar" required id="id_avatar" />
      <input type="submit" value="上传">
    </form>
  </body>
</html>

Python/django/mysite/usr/templates/bookset.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bookset</title>
  </head>
  <body>
    <h1>Form test 2</h1>
    {{a}}
    <form class="" action="" method="post">
    {%csrf_token%}
    {%for field in form%}
    <div>
      {{field.label}}:{{field}}
      {{field.errors}}
    </div>
    {%endfor%}
    <div class = "fieldWrapper">
      <p><input type="submit" value = "添加"></p>
    </div>
    </form>
  </body>
</html>

Python/django/mysite/usr/templates/cache.html
<!-- {%load cache%} -->
<!-- 3.页面中某一部分设置缓冲 -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>缓存</title>
</head>
<body>
  <h1>{{ctime}}</h1>
  <h1>{{ctime}}</h1>
  <!-- {%cache 5 ck%} -->
  <h1>{{ctime}}</h1>
  <h1>{{ctime}}</h1>
  <!-- {%endcache%} -->
</body>
</html>

Python/django/mysite/usr/templates/failure.html
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">

	<title>Failure</title>
	
</head>
<body>
	<div id="name">
		<span>{{reason | safe}}</span>	
	</div>
</body>
</html>

Python/django/mysite/usr/templates/formset.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Formset</title>
  </head>
  <body>
    <h1>Form test 1</h1>
    {{a}}
    <form class="" action="" method="post">
    {%csrf_token%}
    {%for field in form%}
    <div>
      {{field.label}}:{{field}}
      {{field.errors}}
    </div>
    {%endfor%}
    <div class = "fieldWrapper">
      <p><input type="submit" value = "留言"></p>
    </div>
    </form>
  </body>
</html>

Python/django/mysite/usr/templates/index1.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>首页</title>
  </head>
  <body>
    <h1>欢迎登陆:{{current_user}}</h1>
    <a href="/logout">注销</a>
  </body>
</html>

Python/django/mysite/usr/templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>cookie演示</title>
  </head>
  <body>
    <form class="" action="/login/" method="post">
      <input type="text" name="username" value="">
      <input type="password" name="pwd" value="">
      <input type="submit" value="登陆">
    </form>
  </body>
</html>

Python/django/mysite/usr/templates/page.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>分页器演示</title>
  </head>
  <body>

    {%for article in article_list%}
    {{article}}
    {%endfor%}
    <div id="pagination">
    	<ul id="pagination-flickr">
    		{% if article_list.has_previous %}
    		<li class="previous"><a href="?page={{ article_list.previous_page_number }}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}">&laquo;上一页</a></li>
    		{% else %}
    		<li class="previous-off">&laquo;上一页</li>
    		{% endif %}
    		<li class="active">{{ article_list.number }}/{{ article_list.paginator.num_pages }}</li>
    		{% if article_list.has_next %}
    		<li class="next"><a href="?page={{ article_list.next_page_number }}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}">下一页 &raquo;</a></li>
    		{% else %}
    		<li class="next-off">下一页 &raquo;</li>
    		{% endif %}
    	</ul>
    </div>
  </body>
</html>

Python/django/mysite/usr/templates/reg.html
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">

	<title>Reg</title>

</head>
<body>
	<div id="main">
		<div id="header">
			<h1>Create a free Account</h1>
		</div>
		<p>
		<form action="{%url 'reg'%}" method="post" accept-charset="utf-8">
		{%csrf_token%}
		<ul>
		<h2>New User</h2>
		<li>
			{{reg_form.username}}
		</li>
		<li>
			{{reg_form.password}}
		</li>
		<li>
			{{reg_form.email}}
		</li>
		<li>
			{{reg_form.tel}}
		</li>
		<li>
			{{reg_form.avatar}}
		</li>

			<input type="submit" value="Create And Login">
		</ul>
			</form>
		</p>
	</div>
</body>
</html>

Python/django/mysite/usr/templates/request.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  {{scheme}}
  {{body}}
  {{path}}
  {{method}}
  {{content}}
  {{meta}}<br>
  {{addr}}
</body>
</html>

Python/django/mysite/usr/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  {%if error%}
  <p >Please input</p>
  {%endif%}
  <form action="/search_form" method="get">
    <input type="text" name="q" value="">
    <input type="submit" value="提交">
  </form>

</body>
</html>

Python/django/mysite/usr/templates/user_login.html
<html>
<head>
    <title>login</title>
</head>
<body>
    <h1>login</h1>
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <p> username<input type="text" name= "username" value="{{ username }}"></p>
        <p>password<input type="password" name="password" value="{{ password }}">
        <input type="submit" value="Submit">
     </form>
</body>
</html>